"""
Synonym and normalization mappings for product name → HS category matching.
This module helps bridge the gap between free-text product names and the
standardized HS code descriptions used on taxprice.org.
"""

# Brand names to strip (lowercase). Add more as needed.
BRAND_NAMES = {
    "wadi fatma", "al marai", "almarai", "nadec", "saudia", "al safi",
    "nido", "nestle", "kraft", "heinz", "unilever", "maggi", "knorr",
    "lipton", "pepsi", "coca cola", "sprite", "fanta", "mountain dew",
    "red bull", "al kabeer", "americana", "sadia", "kiri", "puck",
    "philadelphia", "nutella", "oreo", "lays", "doritos", "cheetos",
    "kurkure", "tang", "milo", "ovaltine", "cadbury", "mars", "snickers",
    "twix", "kitkat", "bounty", "galaxy", "toblerone", "lindt",
    "godiva", "ferrero", "kinder", "hershey", "m&m", "skittles",
    "haribo", "trolli", "mentos", "tic tac", "halls", "strepsils",
    "colgate", "dove", "lux", "dettol", "lifebuoy", "palmolive",
}

# Product synonym mappings: common name → list of HS description keywords
# The matcher will search for these terms in the HS code descriptions.
PRODUCT_SYNONYMS = {
    # Bakery / pastry
    "cupcake": ["cake", "pastry", "bakery", "pastries"],
    "muffin": ["cake", "pastry", "bakery", "pastries"],
    "brownie": ["cake", "pastry", "bakery", "chocolate"],
    "donut": ["pastry", "bakery", "doughnut", "sweet"],
    "doughnut": ["pastry", "bakery", "doughnut", "sweet"],
    "croissant": ["pastry", "bakery", "bread"],
    "pie": ["pastry", "bakery", "pie"],
    "tart": ["pastry", "bakery", "tart"],
    "cookie": ["biscuit", "bakery", "sweet biscuit"],
    "biscuit": ["biscuit", "bakery", "sweet biscuit"],
    "cracker": ["biscuit", "cracker", "crisp bread"],
    "bread": ["bread", "bakery"],
    "toast": ["bread", "bakery", "toasted"],
    "waffle": ["waffle", "bakery", "pastry"],
    "pancake": ["cake", "pastry", "mix"],

    # Snacks
    "chips": ["potato", "crisps", "snack", "prepared"],
    "crisps": ["potato", "crisps", "snack"],
    "french fries": ["potato", "frozen", "prepared"],
    "fries": ["potato", "frozen", "prepared"],
    "popcorn": ["corn", "prepared", "cereal"],
    "nachos": ["corn", "tortilla", "prepared"],
    "pretzel": ["bakery", "bread", "pretzel"],
    "kurkure": ["extruded", "corn", "snack", "prepared cereal"],

    # Sauces & condiments
    "ketchup": ["tomato ketchup", "tomato sauce"],
    "mayonnaise": ["mayonnaise", "sauce", "condiment"],
    "mustard": ["mustard", "sauce", "condiment"],
    "soy sauce": ["soy sauce", "sauce"],
    "hot sauce": ["sauce", "pepper", "condiment"],
    "bbq sauce": ["sauce", "condiment"],
    "vinegar": ["vinegar", "acetic acid"],
    "pickle": ["preserved", "cucumber", "vegetable"],
    "relish": ["preserved", "condiment"],
    "salsa": ["sauce", "tomato", "prepared"],
    "hummus": ["prepared", "chickpea", "vegetable"],
    "tahini": ["sesame", "paste", "preparation"],

    # Dairy
    "cream": ["cream", "dairy", "milk"],
    "butter": ["butter", "dairy", "fat"],
    "ghee": ["butter", "fat", "oil", "ghee"],
    "cheese": ["cheese", "dairy", "curd"],
    "yogurt": ["yogurt", "yoghurt", "fermented milk"],
    "yoghurt": ["yogurt", "yoghurt", "fermented milk"],
    "milk": ["milk", "dairy", "cream"],
    "ice cream": ["ice cream", "frozen", "dairy"],
    "whey": ["whey", "dairy", "protein"],

    # Beverages
    "juice": ["juice", "fruit", "vegetable", "beverage"],
    "soda": ["water", "aerated", "beverage", "sweetened"],
    "cola": ["water", "aerated", "beverage", "sweetened"],
    "energy drink": ["beverage", "non-alcoholic", "water"],
    "tea": ["tea", "beverage"],
    "coffee": ["coffee", "beverage", "roasted"],
    "cocoa": ["cocoa", "chocolate", "preparation"],
    "smoothie": ["juice", "fruit", "beverage"],
    "milkshake": ["milk", "beverage", "dairy"],
    "water": ["water", "mineral", "aerated"],

    # Confectionery / chocolate
    "chocolate": ["chocolate", "cocoa", "confectionery"],
    "candy": ["sugar confectionery", "sweet", "confectionery"],
    "toffee": ["sugar confectionery", "toffee", "caramel"],
    "caramel": ["sugar confectionery", "caramel"],
    "gum": ["chewing gum", "confectionery"],
    "chewing gum": ["chewing gum", "confectionery"],
    "lollipop": ["sugar confectionery", "sweet"],
    "jelly beans": ["sugar confectionery", "sweet"],
    "marshmallow": ["sugar confectionery", "sweet"],
    "wafer": ["wafer", "biscuit", "chocolate"],

    # Meat / protein
    "chicken": ["poultry", "chicken", "meat", "fowl"],
    "beef": ["bovine", "beef", "meat"],
    "lamb": ["sheep", "lamb", "meat", "ovine"],
    "mutton": ["sheep", "mutton", "meat", "ovine"],
    "goat": ["goat", "meat", "caprine"],
    "sausage": ["sausage", "meat", "prepared"],
    "salami": ["sausage", "meat", "prepared"],
    "burger": ["meat", "prepared", "bovine"],
    "ham": ["meat", "pig", "pork", "ham"],
    "bacon": ["meat", "pig", "pork", "bacon"],
    "nuggets": ["meat", "prepared", "poultry", "chicken"],
    "fish": ["fish", "seafood", "fillet"],
    "tuna": ["tuna", "fish", "prepared"],
    "salmon": ["salmon", "fish"],
    "shrimp": ["shrimp", "crustacean", "prawn"],
    "prawn": ["prawn", "shrimp", "crustacean"],

    # Grains / cereals
    "rice": ["rice", "cereal", "grain"],
    "wheat": ["wheat", "cereal", "grain", "flour"],
    "flour": ["flour", "wheat", "cereal"],
    "pasta": ["pasta", "noodle", "macaroni", "spaghetti"],
    "noodles": ["noodle", "pasta", "vermicelli"],
    "oats": ["oat", "cereal", "rolled"],
    "barley": ["barley", "cereal", "grain"],
    "corn": ["corn", "maize", "cereal"],
    "cereal": ["cereal", "breakfast", "prepared"],

    # Oils & fats
    "olive oil": ["olive oil", "vegetable oil"],
    "sunflower oil": ["sunflower", "vegetable oil"],
    "palm oil": ["palm", "vegetable oil"],
    "coconut oil": ["coconut", "vegetable oil"],
    "vegetable oil": ["vegetable oil", "edible oil"],
    "margarine": ["margarine", "fat", "spread"],

    # Spices
    "salt": ["salt", "sodium chloride"],
    "pepper": ["pepper", "spice"],
    "turmeric": ["turmeric", "spice", "curcuma"],
    "cinnamon": ["cinnamon", "spice"],
    "cumin": ["cumin", "spice"],
    "cardamom": ["cardamom", "spice"],
    "saffron": ["saffron", "spice"],
    "chili": ["chili", "pepper", "capsicum"],
    "paprika": ["paprika", "pepper", "spice"],
    "curry": ["curry", "spice", "mixed"],
    "masala": ["spice", "mixed", "seasoning"],

    # Fruits
    "dates": ["dates", "fruit", "palm"],
    "apple": ["apple", "fruit", "fresh"],
    "banana": ["banana", "fruit", "fresh"],
    "orange": ["orange", "citrus", "fruit"],
    "lemon": ["lemon", "citrus", "fruit"],
    "mango": ["mango", "fruit", "tropical"],
    "grape": ["grape", "fruit", "fresh"],
    "strawberry": ["strawberry", "berry", "fruit"],
    "watermelon": ["watermelon", "melon", "fruit"],
    "pineapple": ["pineapple", "fruit", "tropical"],
    "pomegranate": ["pomegranate", "fruit"],
    "fig": ["fig", "fruit"],
    "raisin": ["raisin", "grape", "dried fruit"],
    "dried fruit": ["dried", "fruit", "preserved"],

    # Vegetables
    "tomato": ["tomato", "vegetable"],
    "potato": ["potato", "vegetable", "tuber"],
    "onion": ["onion", "vegetable", "allium"],
    "garlic": ["garlic", "vegetable", "allium"],
    "cucumber": ["cucumber", "vegetable"],
    "carrot": ["carrot", "vegetable"],
    "lettuce": ["lettuce", "vegetable", "salad"],
    "spinach": ["spinach", "vegetable"],
    "broccoli": ["broccoli", "vegetable", "brassica"],
    "mushroom": ["mushroom", "fungus", "vegetable"],
    "peas": ["peas", "legume", "vegetable"],
    "beans": ["beans", "legume", "vegetable"],
    "lentils": ["lentils", "legume", "pulse"],
    "chickpeas": ["chickpeas", "legume", "pulse"],

    # Sweeteners
    "sugar": ["sugar", "sucrose", "cane"],
    "honey": ["honey", "natural"],
    "syrup": ["syrup", "sugar", "glucose"],
    "jam": ["jam", "fruit", "preserved", "jelly"],
    "marmalade": ["marmalade", "citrus", "jam"],
    "molasses": ["molasses", "sugar", "treacle"],

    # Nuts
    "almond": ["almond", "nut", "shelled"],
    "pistachio": ["pistachio", "nut"],
    "cashew": ["cashew", "nut"],
    "walnut": ["walnut", "nut"],
    "hazelnut": ["hazelnut", "nut"],
    "peanut": ["groundnut", "peanut", "nut"],
    "coconut": ["coconut", "palm"],

    # Prepared / canned
    "canned food": ["preserved", "prepared", "canned"],
    "frozen food": ["frozen", "prepared"],
    "instant noodles": ["noodle", "prepared", "instant"],
    "soup": ["soup", "broth", "prepared"],
    "baby food": ["baby", "infant", "food preparation"],

    # Non-food (common)
    "soap": ["soap", "cleaning", "surface-active"],
    "detergent": ["detergent", "cleaning", "surface-active"],
    "shampoo": ["shampoo", "hair", "preparation"],
    "toothpaste": ["dentifrice", "oral", "preparation"],
    "perfume": ["perfume", "toilet water", "fragrance"],
    "cosmetics": ["cosmetic", "beauty", "preparation"],
    "paper": ["paper", "paperboard", "cellulose"],
    "plastic": ["plastic", "polymer", "synthetic"],
    "textile": ["textile", "fabric", "woven"],
    "clothing": ["garment", "clothing", "apparel"],
    "shoes": ["footwear", "shoe", "sole"],
    "electronics": ["electrical", "electronic", "apparatus"],
    "battery": ["battery", "electric", "accumulator"],
    "phone": ["telephone", "cellular", "mobile"],
    "computer": ["computer", "data processing", "machine"],
    "furniture": ["furniture", "seat", "wood"],
    "toy": ["toy", "game", "sport"],
    "medicine": ["pharmaceutical", "medicament", "drug"],
    "vitamin": ["vitamin", "supplement", "provitamin"],
}

# Chapter descriptions for quick reference
HS_CHAPTER_HINTS = {
    "01": "Live animals",
    "02": "Meat and edible meat offal",
    "03": "Fish and crustaceans",
    "04": "Dairy products; eggs; honey",
    "05": "Products of animal origin, n.e.c.",
    "06": "Live trees and plants",
    "07": "Edible vegetables",
    "08": "Edible fruits and nuts",
    "09": "Coffee, tea, spices",
    "10": "Cereals",
    "11": "Milling products; malt; starch",
    "12": "Oil seeds; misc grains",
    "13": "Lac; gums; resins",
    "14": "Vegetable plaiting materials",
    "15": "Animal/vegetable fats and oils",
    "16": "Preparations of meat/fish",
    "17": "Sugars and sugar confectionery",
    "18": "Cocoa and cocoa preparations",
    "19": "Preparations of cereals/flour/starch/milk; pastry",
    "20": "Preparations of vegetables/fruits/nuts",
    "21": "Miscellaneous edible preparations",
    "22": "Beverages, spirits, vinegar",
    "23": "Residues from food industries; animal feed",
    "24": "Tobacco and manufactured tobacco substitutes",
    "25": "Salt; sulphur; earths; stone",
    "26": "Ores, slag, ash",
    "27": "Mineral fuels, oils",
    "28": "Inorganic chemicals",
    "29": "Organic chemicals",
    "30": "Pharmaceutical products",
    "31": "Fertilizers",
    "32": "Tanning/dyeing extracts; paints",
    "33": "Essential oils; cosmetics; perfumery",
    "34": "Soap; waxes; candles",
    "35": "Albuminoidal substances; glues",
    "36": "Explosives; pyrotechnics",
    "37": "Photographic goods",
    "38": "Miscellaneous chemical products",
    "39": "Plastics",
    "40": "Rubber",
    "41": "Raw hides and skins",
    "42": "Leather articles; handbags",
    "43": "Furskins",
    "44": "Wood and wood articles",
    "45": "Cork",
    "46": "Straw/esparto manufactures; basketware",
    "47": "Pulp of wood",
    "48": "Paper and paperboard",
    "49": "Printed books, newspapers",
    "50": "Silk",
    "51": "Wool; animal hair",
    "52": "Cotton",
    "53": "Other vegetable textile fibres",
    "54": "Man-made filaments",
    "55": "Man-made staple fibres",
    "56": "Wadding; felt; twine; cordage",
    "57": "Carpets",
    "58": "Special woven fabrics",
    "59": "Impregnated textile fabrics",
    "60": "Knitted or crocheted fabrics",
    "61": "Knitted/crocheted apparel",
    "62": "Woven apparel",
    "63": "Other made-up textile articles",
    "64": "Footwear",
    "65": "Headgear",
    "66": "Umbrellas; walking sticks",
    "67": "Prepared feathers; artificial flowers",
    "68": "Stone/plaster/cement articles",
    "69": "Ceramic products",
    "70": "Glass and glassware",
    "71": "Pearls; precious stones; metals; coins",
    "72": "Iron and steel",
    "73": "Iron/steel articles",
    "74": "Copper",
    "75": "Nickel",
    "76": "Aluminium",
    "78": "Lead",
    "79": "Zinc",
    "80": "Tin",
    "81": "Other base metals",
    "82": "Tools; cutlery of base metal",
    "83": "Miscellaneous base metal articles",
    "84": "Nuclear reactors; boilers; machinery",
    "85": "Electrical machinery and equipment",
    "86": "Railway/tramway locomotives",
    "87": "Vehicles (not railway)",
    "88": "Aircraft; spacecraft",
    "89": "Ships; boats",
    "90": "Optical; medical instruments",
    "91": "Clocks and watches",
    "92": "Musical instruments",
    "93": "Arms and ammunition",
    "94": "Furniture; bedding; lamps",
    "95": "Toys; games; sports",
    "96": "Miscellaneous manufactured articles",
    "97": "Works of art; antiques",
}
